# Book settings
title: "Optimal Income-Based Traffic Fines with Labor Supply Responses"
author: "Author Name"
copyright: "2024"
logo: ""

# Don't execute notebooks (they have saved outputs)
execute:
  execute_notebooks: "off"
  timeout: 600
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: traffic_fines_paper.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/MaxGhenis/traffic-fine-sim
  path_to_book: paper
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  
# Bibliography
bibtex_bibfiles:
  - references.bib
  
sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js